### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by weand** [opendistro-for-elasticsearch/job-scheduler#20]
Hi, 

do you have plans to publish Artifacts to Maven Central. As an enduser I would expect to find them there.

Regards
Andreas

**Comment by alolita** [comment]
@weand - Totally. We're in the process of pushing the Maven Central artifacts for version 1.0.0 These should be available shortly. Thanks for your patience :-)

**Comment by weand** [comment]
One further question regarding the artifacts that will be deployed to maven central. Are you going to compile them with JDK 12, like the main plugin? Would that mean, that SPI developers would also have to use JDK 12.

From my perspective it would make sense to better compile against the latest JDK LTS version, which is JDK 11 at the moment. I assume that newer non-LTS versions aren't widely adopted by the community.

Also opendistro itself currently runs with JDK 11, so it would make sense to use JDK 11 for the job scheduler as well. I'm wondering how job-scheduler compiled against JDK 12 can even work with Opendistro running on JDK 11?

**Comment by zengyan-amazon** [comment]
Hi @weand ,

Sorry for the delayed response.

Yes, we use JDK 12 to build this JobScheduler plugin, because Elasticsearch 7 requires JDK12 to build plugins. Even we use JDK 12 as our compiler, we still specify the source and target compatibility to 1.8 [in our build logic](https://github.com/opendistro-for-elasticsearch/job-scheduler/blob/master/build.gradle#L84), so that this plugin can run on JDK 8, 10, 11 and 12

Hope this answers your question.

**Comment by zengyan-amazon** [comment]
JobScheduler spi has been released to MavenCentral starting OpenDistroForElasticsearch 1.0. https://mvnrepository.com/artifact/com.amazon.opendistroforelasticsearch/opendistro-job-scheduler-spi
