### ISSUE TITLE
Opendistro job scheduler

### ISSUE THREAD

**Issue by vishalrijhwani** [opendistro-for-elasticsearch/job-scheduler#90]
To make job scheduler plugin work in cluster, do i need to install plugin in single node of cluster or all nodes of cluster, please reply

**Comment by dbbaughe** [comment]
Job scheduler plugin is developed to be installed on all nodes of cluster, mainly because it listens to local indexing/delete operations for shards that are located on that node, so if you only installed in a single node and there were some shards of other plugins using it on other nodes then those jobs would not get scheduled.
